# Setup McCoy Group config
title: McCoy Group References
url: "https://mccoygroup.github.io/References" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  McCoyGroup
footer_text: >-
  Brought to you by the McCoy Group at the University of Washington
sitemap_roots:
  - name: McCode Academy
    url: /McCoy%20Group%20Code%20Academy/
    listing:
      - name: Getting Started
        url: /McCoy%20Group%20Code%20Academy/GettingStarted/
      - name: NumPy
        url: /McCoy%20Group%20Code%20Academy/NumPy/
      - name: Data & IO
        url: /McCoy%20Group%20Code%20Academy/DataIO/
      - name: Plotting
        url: /McCoy%20Group%20Code%20Academy/Plotting/
      - name: Exercises
        url: /McCoy%20Group%20Code%20Academy/Exercises/
      - name: Programming Best-Practices
        url: /McCoy%20Group%20Code%20Academy/ProgrammingTips/
      - name: Tips and Tricks
        url: /McCoy%20Group%20Code%20Academy/TipsAndTricks/
      - name: Contributing
        url: /McCoy%20Group%20Code%20Academy/Contributing.html
  - name: References
    url: /References/
    listing:
      - name: Intro to Quantum
        url: /References/Intro%20To%20Quantum/
      - name: Basis Set Methods
        url: /References/Basis%20Set%20Methods/
      - name: Monte Carlo Methods
        url: /References/Monte%20Carlo%20Methods/
      - name: Spectrum Generation
        url: /References/Spectrum%20Generation/
  - name: Documentation
    depth: 2
links:
  - url: https://blogs.uw.edu/mccoygrp/
    title: Group Website
  - url: https://github.com/McCoyGroup
    title: GitHub
  - url: https://stackoverflow.com/c/mccoygroup/questions
    title: Stack Overflow

# Build settings
markdown: kramdown
remote_theme: McCoyGroup/finx
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-optional-front-matter
relative_links:
  enabled: true

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
  - scope:
      path: "index.html|about.html|404.html|search.html"
    values:
      layout: "page"
  - scope:
      path: "McCoy Group Code Academy"
      type: "pages"
    values:
      optional_scripts: true
      custom_styles: "refs"
      layout: "refs"
  - scope:
      path: "References"
      type: "pages"
    values:
      optional_scripts: true
      custom_styles: "refs"
      layout: "refs"
  - scope:
      path: "Documentation"
      type: "pages"
    values:
      optional_scripts: true
      annotations_type: "refs"
      custom_styles: "refs"
      layout: "refs"

# Exclude from processing
exclude:
  - Documentation/examples
  - Documentation/templates
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
