# Setup McCoy Group config
title: McCoy Group References
description: References, resources, and tutorials for the study of large amplitude molecular motions
url: "https://mccoygroup.github.io/References" # the base hostname & protocol for your site, e.g. http://example.com
icon: favicon.png
github_username:  McCoyGroup
footer_text: >-
  Brought to you by the McCoy Group at the University of Washington
#sitemap_depth: 2
sitemap_roots:
  - name: McCode Academy
    url: /McCoy%20Group%20Code%20Academy/
    listing:
      - name: Getting Started
        url: /McCoy%20Group%20Code%20Academy/GettingStarted/
      - name: NumPy
        url: /McCoy%20Group%20Code%20Academy/NumPy/
      - name: Data & IO
        url: /McCoy%20Group%20Code%20Academy/DataIO/
      - name: Plotting
        url: /McCoy%20Group%20Code%20Academy/Plotting/
      - name: Exercises
        url: /McCoy%20Group%20Code%20Academy/Exercises/
      - name: Programming Tips
        url: /McCoy%20Group%20Code%20Academy/ProgrammingTips/
      - name: Supercomputing at UW
        url: /McCoy%20Group%20Code%20Academy/Supercomputing101/
  - name: References
    url: /References/
    listing:
      - name: Basis Set Methods
        url: /References/Basis%20Set%20Methods/
      - name: Monte Carlo Methods
        url: /References/Monte%20Carlo%20Methods/
      - name: Spectrum Generation
        url: /References/Spectrum%20Generation/
  - name: Python Packages
    url: /PyVibPackages/
    listing:
      - name: PyVibDMC
        url: /PyVibPackages/PyVibDMC/
      - name: PyVibPTn
        url: /PyVibPackages/PyVibPTn/
links:
  - url: https://sites.uw.edu/mccoygrp/
    title: Group Website
  - url: https://github.com/McCoyGroup
    title: GitHub
  - url: https://stackoverflow.com/c/mccoygroup/questions
    title: Stack Overflow

# Build settings
markdown: kramdown
remote_theme: McCoyGroup/finx
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-optional-front-matter
  - jekyll-seo-tag
relative_links:
  enabled: true

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
      image: "https://mccoygroup.github.io/References/img/logo_m.png"
  - scope:
      path: "index.html|about.html|404.html|search.html"
    values:
      layout: "page"
  - scope:
      path: "McCoy Group Code Academy"
      type: "pages"
    values:
      optional_scripts: true
      custom_styles: "refs"
      layout: "refs"
      breadcrumbs:
        num_links: 1
        min_depth: 0
        check_urls: false
  - scope:
      path: "References"
      type: "pages"
    values:
      optional_scripts: true
      custom_styles: "refs"
      layout: "refs"
      breadcrumbs:
        num_links: 1
        min_depth: 0
        check_urls: false
  - scope:
      path: "Documentation"
      type: "pages"
    values:
      optional_scripts: true
      annotations_type: "refs"
      custom_styles: "refs"
      layout: "docs"
      sidebar_visible: true
      breadcrumbs:
        num_links: 1
        min_depth: 0
        check_urls: false
        url_ext: ".html"

# Exclude from processing
exclude:
  - Documentation/examples
  - Documentation/templates
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
