# Copied directly from here: https://github.com/jupyterlab/jupyterlab-demo/blob/master/binder/environment.yml
channels:
 - conda-forge
dependencies:
 # Jupyter
 - jupyterlab=2
 - nodejs=11
 - nbconvert=5.5
 - widgetsnbextension=3.5
 # Python Kernel
 - ipykernel=5.1
 - ipywidgets=7.5
 - ipyleaflet=0.12
 - matplotlib=3.1
 - python=3.7
 - seaborn=0.9
 - pyyaml
 - traittypes==0.2.1
 - invoke=1.2