on:
  push:
    branches:
      - gh-pages

name: McBuild site
jobs:
  mcbuild_site:
    runs-on: ubuntu-latest
    name: Build out group webstite
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: McBuild site
        uses: ./build_site # Uses an action in the root directory